# Basic Settings
theme: jekyll-theme-minimal
title: Aarohi Panicker's homepage
description: Bookmark this to keep an eye on my project updates!

# URL Configuration
baseurl: "/subdirectory"

# Permalinks
permalink: /:year/:month/:day/:title/

# Excluding Files
exclude:
  - Gemfile
  - Gemfile.lock

# Markdown Configuration
markdown: kramdown

# Pagination
paginate: 5

# Date Format
date_format: "%B %-d, %Y"

# Collections
collections:
  my_collection:
    output: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
